(define xmas-px (lambda (x m a s) (display "px") (display " -> ") (if (< a 2006) (xmas-qkq x m a s) (if (> m 2090) (quote accept) (xmas-rfg x m a s)))))
(define xmas-pv (lambda (x m a s) (display "pv") (display " -> ") (if (> a 1716) (quote reject) (quote accept))))
(define xmas-lnx (lambda (x m a s) (display "lnx") (display " -> ") (if (> m 1548) (quote accept) (quote accept))))
(define xmas-rfg (lambda (x m a s) (display "rfg") (display " -> ") (if (< s 537) (xmas-gd x m a s) (if (> x 2440) (quote reject) (quote accept)))))
(define xmas-qs (lambda (x m a s) (display "qs") (display " -> ") (if (> s 3448) (quote accept) (xmas-lnx x m a s))))
(define xmas-qkq (lambda (x m a s) (display "qkq") (display " -> ") (if (< x 1416) (quote accept) (xmas-crn x m a s))))
(define xmas-crn (lambda (x m a s) (display "crn") (display " -> ") (if (> x 2662) (quote accept) (quote reject))))
(define xmas-in (lambda (x m a s) (display "in") (display " -> ") (if (< s 1351) (xmas-px x m a s) (xmas-qqz x m a s))))
(define xmas-qqz (lambda (x m a s) (display "qqz") (display " -> ") (if (> s 2770) (xmas-qs x m a s) (if (< m 1801) (xmas-hdj x m a s) (quote reject)))))
(define xmas-gd (lambda (x m a s) (display "gd") (display " -> ") (if (> a 3333) (quote reject) (quote reject))))
(define xmas-hdj (lambda (x m a s) (display "hdj") (display " -> ") (if (> m 838) (quote accept) (xmas-pv x m a s))))
(define (run) 
		      (let ((total 0))
                   (begin
  (newline)
  (when (eq? 'accept (xmas-in 787 2655 1222 2876))
        (let ((tot (+ 787 2655 1222 2876)))
          (display "ACCEPT : ")
          (display tot)
          (set! total (+ total tot)))))
(begin
  (newline)
  (when (eq? 'accept (xmas-in 1679 44 2067 496))
        (let ((tot (+ 1679 44 2067 496)))
          (display "ACCEPT : ")
          (display tot)
          (set! total (+ total tot)))))
(begin
  (newline)
  (when (eq? 'accept (xmas-in 2036 264 79 2244))
        (let ((tot (+ 2036 264 79 2244)))
          (display "ACCEPT : ")
          (display tot)
          (set! total (+ total tot)))))
(begin
  (newline)
  (when (eq? 'accept (xmas-in 2461 1339 466 291))
        (let ((tot (+ 2461 1339 466 291)))
          (display "ACCEPT : ")
          (display tot)
          (set! total (+ total tot)))))
(begin
  (newline)
  (when (eq? 'accept (xmas-in 2127 1623 2188 1013))
        (let ((tot (+ 2127 1623 2188 1013)))
          (display "ACCEPT : ")
          (display tot)
          (set! total (+ total tot)))))

          (newline)
          (display "results : ")
          (display (list 'total total))
          (newline)
                    ))
         (run)
        