

(define puzzle '(
		 (broadcast sr gd mg hf)
 (flipflops
  ( jb   ps)
  ( cm   ps  tm)
  ( sl   ml  cp)
  ( qr   ml)
  ( hf   kh  jg)
  ( jg   kk)
  ( jt   pq)
  ( qv   kv)
  ( rj   mm  kh)
  ( kf   xt)
  ( kx   vk  mk)
  ( dq   qn)
  ( jk   hh  ps)
  ( rr   mk  nh)
  ( hs   kh  mb)
  ( mg   mk  kf)
  ( xt   dq  mk)
  ( mq   nt)
  ( nh   bm)
  ( md   hs)
  ( vk   mk  vl)
  ( mm   kh)
  ( kc   ps  jk)
  ( kk   dm)
  ( jn   ll  ml)
  ( pp   kh  md)
  ( zf   ml  bd)
  ( qx   pp)
  ( qn   rr)
  ( mb   qb  kh)
  ( nt   jt)
  ( vl   zk  mk)
  ( gd   ml  rm)
  ( hh   ps  jb)
  ( tm   ps  mq)
  ( kv   jn  ml)
  ( zs   kc)
  ( ll   ml  kq)
  ( cp   qv  ml)
  ( rm   sl  ml)
  ( bd   qr  ml)
  ( dm   qx)
  ( qb   rj  kh)
  ( pq   zs)
  ( bm   kx)
  ( sr   cm  ps)
  ( zk   mk)
  ( kq   zf))

 (conjunctions
  ( ps   xc  mq  jt  zs  sr  nt  pq)
  ( xc   zh)
  ( ml   bp  gd  qv  kq)
  ( th   zh)
  ( zh   rx)
  ( pd   zh)
  ( kh   jg  qx  md  th  hf  dm  kk)
  ( mk   kf  qn  nh  pd  dq  mg  bm)
  ( bp   zh))
 ))


;; (load "example2.scm")
(load "solver.scm")
;; (part1)
;; (32000000 8000 4000)

(define (push)
  ;; broadcast sends a low pulse to [ sr gd mg hf ]
  (incf low-pulse-sent-count)
  (sr 'pulse (low) 'broadcast)
  (incf low-pulse-sent-count)
  (gd 'pulse (low) 'broadcast)
  (incf low-pulse-sent-count)
  (mg 'pulse (low) 'broadcast)
  (incf low-pulse-sent-count)
  (hf 'pulse (low) 'broadcast)  
  (keep-working))

;; sr gd mg hf
;; (product = 886701120 low= 17984 high= 49305)

;; SOLVED !!!
;; lets go home ...

